export const theme = {
  accent: "cyan",
  accentBright: "cyanBright",
  ok: "green",
  warn: "yellow",
  err: "red",
  user: "blue",
  muted: "gray",
  border: "cyan",
  borderActive: "green",
  borderErr: "red",
  inputBg: "#1e1e1e",
  userAccent: "#5f87ff",
  userBlockBg: "#1c1c1c",
  menuSelectedBg: "#e0a065",
  menuSelectedFg: "black",
  menuText: "white",
  menuDesc: "#9aa0a6",
  questionBar: "#c678dd",
  questionLink: "#61afef",
  selectionBg: "#cfcfcf",
  selectionFg: "#111111",
  toastBg: "#262626",
  toastBar: "#4aa8c0",
  toastFg: "#ffffff",
};
